pool:
  vmImage: 'macOS-latest'

trigger:
  branches:
    include:
      - 'main'

name: $(Build.BuildId)

stages:
  - stage: qa
    displayName: 'Run Automation Test - QA'
    dependsOn: []
    jobs:
      - template: playwright_template.yml
        parameters:
          BASE_URL: 'http://example.com'  # Set a valid URL here if needed
