parameters:
  - name: BASE_URL
    type: string

jobs:
  - job: Test
    displayName: 'Run Simple Test'
    steps:
      - script: echo "Running tests with BASE_URL: ${{ parameters.BASE_URL }}"
        displayName: 'Echo BASE_URL'