parameters:
  - name: BASE_URL
    type: string

jobs:
  - job: Test
    displayName: 'Run Playwright Tests'
    steps:
      - script: |
          echo "Running tests with BASE_URL: ${BASE_URL}"
        displayName: 'Echo BASE_URL'
